/* eslint-disable @next/next/no-img-element */
import { Country } from '@/types';
import styles from '@/styles/Detail.module.css';
import Head from 'next/head';
import path from 'path';
import fs from 'fs';
import { formatNumber } from '@/utils';

interface Props {
	country: Country;
}

function details({ country }: Props) {
	const title = `${country.name} | GCountries`;
	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles.container}>
				<main className={styles.main}>
					<div className={styles.flag}>
						<img src={country.flag} alt={`flag of ${country.name}`} />
					</div>
					<div className={styles.detail}>
						<h2>{country.name}</h2>
						<div className={styles.info}>
							<ul>
								<li>
									<span>Native Name:</span> {country.name}
								</li>
								<li>
									<span>Other Names:</span> {country.altSpellings?.toString() ?? ''}
								</li>
								<li>
									<span>Demonym:</span> {country.demonym}
								</li>
								<li>
									<span>Currencies:</span> {country.currencies?.map((c) => c.name)}
								</li>
								<li>
									<span>Regional Bloc:</span>{' '}
									{country.regionalBlocs?.length ? country.regionalBlocs.map((m) => m.acronym) : 'None'}
								</li>
							</ul>
							<ul>
								<li>
									<span>Region:</span> {country.region}
								</li>
								<li>
									<span>Subregion:</span> {country.subregion}
								</li>
								<li>
									<span>Capital:</span> {country.capital ?? ''}
								</li>
								<li>
									<span>Population:</span> {formatNumber(country.population) ?? ''}
								</li>
							</ul>
						</div>
						<div className={styles.borders}>
							<h4>Border Countries:</h4>
							<div>{country.borders?.toString()}</div>
						</div>
					</div>
				</main>
			</div>
		</>
	);
}

export default details;

export const getStaticPaths = async () => {
	const dataFilePath = path.join(process.cwd(), 'public', 'data', 'countries.json');
	const jsonData: Country[] = JSON.parse(fs.readFileSync(dataFilePath, 'utf8'));

	const paths = jsonData.map((d) => {
		return {
			params: {
				code: d.alpha3Code,
			},
		};
	});

	return {
		paths,
		fallback: false,
	};
};

export const getStaticProps = async (context: any) => {
	const { code } = context.params;
	const dataFilePath = path.join(process.cwd(), 'public', 'data', 'countries.json');
	const jsonData: Country[] = JSON.parse(fs.readFileSync(dataFilePath, 'utf8'));

	const data = jsonData.find((d) => d.alpha3Code === code);

	return {
		props: {
			country: data,
		},
	};
};
