export const REGIONS = ['Asia', 'Europe', 'Africa', 'Oceania', 'Americas', 'Polar', 'Antarctic Ocean', 'Antarctic'];

export const SUB_REGIONS = [
	'Southern Asia',
	'Northern Europe',
	'Southern Europe',
	'Northern Africa',
	'Polynesia',
	'Middle Africa',
	'Caribbean',
	'Antarctica',
	'South America',
	'Western Asia',
	'Australia and New Zealand',
	'Central Europe',
	'Eastern Europe',
	'Western Europe',
	'Central America',
	'Western Africa',
	'Northern America',
	'Southern Africa',
	'South Antarctic Ocean',
	'Eastern Africa',
	'South-Eastern Asia',
	'Eastern Asia',
	'Melanesia',
	'Micronesia',
	'Antarctic',
	'Central Asia',
	'North America',
];

export const REGIONAL_BLOCS = [
	'AL',
	'ASEAN',
	'AU',
	'CAIS',
	'CARICOM',
	'CEFTA',
	'EEU',
	'EFTA',
	'EU',
	'NAFTA',
	'PA',
	'SAARC',
	'USAN',
];
