import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Country } from '@/types';
import Card from '@/components/Card';

interface Props {
	countries: Country[];
}

export default function Home({ countries }: Props) {
	return (
		<>
			<Head>
				<title>Browse | GCountries</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.container}>
				<div className={styles.card_container}>
					{countries && countries.map((c) => <Card key={c.name.common} country={c} />)}
				</div>
			</main>
		</>
	);
}

export const getStaticProps = async () => {
	const res = await fetch('https://restcountries.com/v3.1/all');
	const data = await res.json();
	return {
		props: {
			countries: data,
		},
	};
};
